### ISSUE TITLE
Ability for vertices to remember their positions.

### ISSUE THREAD

**Issue by robertonic** [brunomnsilva/JavaFXSmartGraph#1]
I'm trying to use JavaFXSmartGraph to show relationships between people. 

It works well but a lot of manual repositioning is required each time the graph is shown to get the layout right.  This happens whichever layout strategy is used. 

E.g. The circular layout strategy produces this:

![image](https://user-images.githubusercontent.com/7998815/72625693-27b43380-3941-11ea-8350-77be69537e5b.png)

But after manual changes it's clearer: 

![image](https://user-images.githubusercontent.com/7998815/72625796-60540d00-3941-11ea-96ce-ada142056df1.png)

Is there some way for the graph to remember previous node positions and to use these if they have been set before?

**Comment by brunomnsilva** [comment]
Hi,

I think what you ask for can be achieved with a custom placement strategy. You can create your own class which implements `SmartPlacementStrategy` and internally use a Map in which you store, e.g., the element of a vertex (via a `SmartGraphVertex`) mapped onto its position (new or previous).

The strategy method gives you all the information needed to achieve this:

`public <V,E> void place(double width, double height, Graph<V,E> theGraph, Collection<? extends SmartGraphVertex<V>> vertices);`

Since the strategy passed onto the constructor of the visualization is an instance of an object, you can recicle it between displaying graphs. 

I believe your specific problem arises in trying to show the same updated graph between new instances of the `SmartGraphPanel`. The provided solution should work in this case, that's why I suggest mapping the vertices elements and not the vertices themselves, which will have different addresses/references in a new instance of the visualization.

-----

Otherwise, just maintain the base visualization instance around (e.g., show / hide) and update it via `graphView.update()`; all the previously placed vertices will maintain their positions (if not using automatic placement, that is).

**Comment by robertonic** [comment]
Thanks for the help.

I'll try implementing the SmartPlacementStrategy interface.

The code reads the values from disk so it needs to retain the information
between sessions.  How do I access the new positions of nodes after they
have been moved?

**Comment by brunomnsilva** [comment]
Did you manage to find a solution?

For your specific situation, maybe I need to add some getters to the `SmartGraphVertex` interface so you can get those values.

**Comment by robertonic** [comment]
Hi Bruno

Unfortunately no. I  subclassed  SmartPlacementStrategy but I couldn't find
a way to get the new node position when nodes were moved. As I mentioned I
save and load the graph so I need to keep the new positions and restore
them later.

>> maybe I need to add some getters to the SmartGraphVertex interface so
you can get those values.

Yes.  If I could set the vertex positions if necessary in the place()
method and get the updated positions on exit that would be useful.

Regards

Rob

**Comment by brunomnsilva** [comment]
I've added the needed methods in the latest commit. Now you should be able to obtain the positions and set them later on! 😃 


```
/**
     * Return the center x-coordinate of this vertex in panel coordinates.
     * 
     * @return     x-coordinate of the vertex 
     */
    public double getPositionCenterX();
    
    /**
     * Return the center y-coordinate of this vertex in panel coordinates.
     * 
     * @return     y-coordinate of the vertex 
     */
    public double getPositionCenterY();
```

**Comment by robertonic** [comment]
Hi Bruno

Thank you!. That works perfectly.

One other request.  Methods to get/set a unique id for each
SmartGraphVertex would be helpful. Currently, I need to use the vertex name
to identify it. I'm using items which all have a visible name and an id.
The IDs are unique but the names may not be. If you like I could add these
in a fork.

Rob
