### ISSUE TITLE
setStyleClass adds class instead of setting it.

### ISSUE THREAD

**Issue by Bertie2011** [brunomnsilva/JavaFXSmartGraph#10]
In an application where styles are constantly changed, the setStyleClass does not remove the previously "set" style, resulting in visuals not updating.

**Comment by brunomnsilva** [comment]
You're right. It was bad testing on my part. The code now resets all previous styling:

![image](https://user-images.githubusercontent.com/16222114/82369066-58e76200-9a0e-11ea-8b23-3990010461e2.png)

This is performed in vertices and edges.

I've committed the fix now. Thanks for pointing it out! :smile:

**Comment by Bertie2011** [comment]
Umm, are you certain it doesn't clear the default classes now? (.vertex, .edge, .arrow)

I love the library by the way, it seems to be the highest quality open source one out there

**Comment by brunomnsilva** [comment]
Thanks! :smile: I made it for my students to use in their applications, because I couldn't find simple java fx libraries for them to use in simple visualizations.

I've tested in the application's main example: if you double click a vertex now it clears all previous styling (see the initially yellow vertex, for example). Before, it didn't seem to work. But please check in the latest commit.
