### ISSUE TITLE
Arrow head size + styling

### ISSUE THREAD

**Issue by Bertie2011** [brunomnsilva/JavaFXSmartGraph#11]
Since the response has been great on a couple bigger issues, I decided to post a couple small ones too.

You can basically resize anything, the edges, the vertices, except for the arrow head. Yes you can change stroke width, but then it turns into a blob instead of a bigger arrow. After diving into the source code it turns out the arrow is a Path element with static coordinates.

Perhaps you could define the path based on stroke width? Or add a property I guess.
While we're on topic of arrow styling, maybe the style classes set on the edge should also appear on the arrow head.

**Comment by brunomnsilva** [comment]
Yep, the arrow heads have static dimensions :disappointed: 

I can add a property, but that requires a bigger code refactoring, since the properties are an attribute of the panel. I'd have to pass down that value to the arrows.

For the arrow styling, there is a separate css class. But, I see that there is currently no way to change the style of the arrows on-the-fly..
