### ISSUE TITLE
Input/output ports on a digraph's vertex?

### ISSUE THREAD

**Issue by bnamestka** [brunomnsilva/JavaFXSmartGraph#16]
Bruno, nice work.  Any thought to including input/output port(s) on the vertex so that data could be associated with that graphic?  It would be a great enhancement for my application.

**Comment by brunomnsilva** [comment]
Thanks, @bnamestka . Hope its useful!

I didn't quite understand what you meant by input/output ports. Care to clarify with a descriptive example?

**Comment by Bertie2011** [comment]
As far as I know, vertexes are representing the data structure for the SmartGraphPanel to understand what to draw. A Vertex has a generic type that can be used to insert your own data class into. That data class should be the one having information about inputs/outputs as it's probably domain specific.

SmartGraphVertex\<T>: JavaFX View representation
Vertex\<T>: The model version, used by SmartGraph to create visual representations
T: Your own data class for domain logic, connections and what not.
(Correct me if I'm wrong)

The reason I'm writing this is that I don't think it would be a good idea to force domain logic/knowledge (about directional connections for example) into the Vertex class. Data association should stay separated from the vertex class.

**Comment by brunomnsilva** [comment]
Hm, yes. The SmartGraphPanel "just" represents an underlying graph. The graph must adhere to the `Graph<V,E>` or Digraph<V,E> interfaces where:

- `V` is the type of element stored in a `Vertex<V>`
- `E` is the type of element stored in an `Edge<E, V>` ; edges always connect vertices.

Directional connections should only be used if the graph is a "digraph". Otherwise, the corresponding property should be changed to *false*:

```
# only makes sense if displaying an oriented graph 
edge.arrow = true
```

The inner workings and graphical representations are dependent of the included `Graph<V,E>` behavior. Changing it, would require a complete rewrite of the library.
